Нужно больше функций
htmlacademy-javascript/1805357-keksobooking-24 pull request #2
Opened 2021-09-25 15:17 UTC by Karaterra

Есть сомнения в правильности, т.к. если максимальное значение диапазона включать, то значения выходят за его рамки, а если не включать, то остаются в рамках.

2021-09-26 16:26 UTC, KrapivinAV requested changes
Движешься в верном направлении )
Надо поправить некоторые моменты и думаю будет нормально.

2021-09-26 16:26 UTC, KrapivinAV commented on js/main.js
> +const myResultInt = function getRandomIntNumber (from, to) {
Здесь надо определиться с несколькими моментами:
1) Прочесть информацию по теме Function Expression vs Function Declaration (например, https://learn.javascript.ru/function-expressions#function-expression-v-sravnenii-s-function-declaration) и решить, что больше нравится. У тебя получилась смесь двух методов сразу )))
2) Обратить внимание на критерии относительно данного момента: 
 - https://up.htmlacademy.ru/javascript/24/criteries#b6
 - https://up.htmlacademy.ru/javascript/24/criteries#d5
3) Рекомендую (можно не принимать во внимание) использовать стрелочные функции...
4) Дополнительно к п.2. - обрати особое внимание на наименование функций - оно должно содержать глагол.

2021-09-26 16:26 UTC, KrapivinAV commented on js/main.js
> +  if (from >= 0 && to >= 0 && from !== to) {
Здесь тоже несколько моментов ):
1) При работе с функциями есть одна некрасивая проблема - замалчивание ошибки. Это такая ситуация, когда при некорректной работе функции она ничего не сообщает наружу об этом. Например, в твоем случае, если твои условия не выполняться, то функция вообще ничего не вернет - это не есть хорошо. Надо внедрить, так называемую, обработку ошибок - рассмотреть все возможные варианты входных данных (аргументов) и на каждый выполнять какое-либо действие или возвращать какое-то значение. Подумай, как соблюсти все условия прописанные в данном задании.
2) Переменные, функции, параметры и т.п. лучше называть поподробнее, чтобы потом самому и коллегам было удобно понимать, для чего они служат.

2021-09-26 16:26 UTC, KrapivinAV commented on js/main.js
> +myResultInt (2, 12);
Вот, здесь, как раз видно, что ты вызываешь функцию, но названа она не в соответствии с критерием Б6.

2021-09-26 16:26 UTC, KrapivinAV commented on js/main.js
> +const myResultFloat = function getRandomIntInclusive(from, to, signsAfter) {
К данной функции вопросы аналогичные предыдущей

2021-09-26 16:26 UTC, KrapivinAV commented on js/main.js
> +    const numFloat = Math.random() * (to - from + 1) + from; //Максимум и минимум включаются
Подумай насчет выбранного шага... +1, наверно, не совсем... Посмотри MDN (https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Math/random)

2021-09-26 16:39 UTC, Karaterra commented on js/main.js
> +// eslint-disable-next-line no-unused-vars
А как иначе? Как мне переменную использовать, если ее не надо использовать? А на вывод в консоль вообще ругается, пишет это не консоль.

2021-09-26 16:40 UTC, Karaterra commented on js/main.js
> +const myResultInt = function getRandomIntNumber (from, to) {
Да. это я пробовал несколькими способами и в итоге осталась ошибка. на которую никто из программ-проверяльщиков не отреагировал. Поправлю.

2021-09-26 16:40 UTC, Karaterra commented on js/main.js
> +const myResultInt = function getRandomIntNumber (from, to) {
getRandomIntNumber - разве не глагол get?

2021-09-26 16:41 UTC, Karaterra commented on js/main.js
> +  if (from >= 0 && to >= 0 && from !== to) {
Да, тут просто, добавлю вывод ошибки по ветке else.

2021-09-26 16:43 UTC, Karaterra commented on js/main.js
> +myResultInt (2, 12);
Ок.

2021-09-28 09:34 UTC, KrapivinAV approved these changes
В основном назначении функций вроде разобрались... Я написал, тебе небольшой недочет, но задание уже закрою... Допилим данную вспомогательную функцию позже, когда понадобится...

2021-09-28 09:34 UTC, KrapivinAV commented on js/main.js
> +      if (fromStart <= toFinish) {
В случае равенства минимального и максимального значений необходимо возвращать от же значение, т.е. расчет по выбранной формуле вести уже нельзя. Но это не ошибка в общем. Поэтому данный случай надо было отсечь отдельным условием.

2021-09-28 09:34 UTC, merged