Правда или действие (часть 1)
htmlacademy-javascript/1805357-keksobooking-24 pull request #7
Opened 2021-10-26 17:23 UTC by Karaterra

---
:mortar_board: [Правда или действие (часть 1)](https://up.htmlacademy.ru/javascript/24/user/1805357/tasks/14)

:boom: https://htmlacademy-javascript.github.io/1805357-keksobooking-24/7/

2021-10-31 13:18 UTC, KrapivinAV requested changes
Осталось немного доделать... Верни плейсхолдер (показал в видео)

2021-10-31 13:18 UTC, KrapivinAV commented on js/form/set-active-mode.js
> +  const formFieldsets = adForm.querySelectorAll('fieldset');
лучше коллекции искать один раз - сделай это на верхнем уровне (и везде далее)

2021-10-31 13:18 UTC, KrapivinAV commented on js/form/validate-form.js
> +      switch (valueSelect) {
помни о принципе DRY - заведи функции как я тебе в видео говорил

2021-10-31 13:18 UTC, KrapivinAV commented on js/form/validate-form.js
> +  changeValueTypeToPrice();
Считаю, что от данных функций можно избавиться

2021-10-31 13:18 UTC, KrapivinAV commented on js/form/validate-form.js
> +          if (offerRoomNumber.value === '2') {
Посмотри ТЗ - там требования по валидации количества гостей другие

2021-10-31 13:18 UTC, KrapivinAV commented on js/form/validate-form.js
> +  adForm.addEventListener('submit', (evt) => {
Пока это все лишнее

2021-11-01 15:58 UTC, KrapivinAV requested changes
Привет, осталось немного.
Еще один момент - у тебя при очистке формы не сбрасывается плейсхолдер в стоимости. Просмотри вообще поведение полей формы в различных ситуациях...

2021-11-01 15:58 UTC, KrapivinAV commented on js/data/variables.js
> +const offerTitle = document.getElementById('title');
Ну, с выносом поиска элементов ты немного переборщил ) Константы, вспомогательные массивы, объекты, словари, перечисления и т. д. можно. Но такие вещи не надо...

2021-11-01 15:58 UTC, KrapivinAV commented on js/data/variables.js
> +const capacities = [
Подход в общем рабочий, но в данном случае, ты мог обойтись значениями, которые принимают поля room_number и capacity. Посмотри на них повнимательнее - их можно сравнивать или, например, привести к числу и посравнивать...

2021-11-01 15:58 UTC, KrapivinAV commented on js/form/validate-form.js
> +      } else if (item.type === offerType.value) {
Срабатыввание данного условия как-то неочевидно... Вроде работает...

2021-11-01 15:58 UTC, KrapivinAV commented on js/form/validate-form.js
> +  offerCost.addEventListener('input', () => {
здесь и в следующем "слушателе событий" ты объявляешь две разные анонимные функции и повторяешь один и тот же фрагмент кода - могут покарать (см. https://up.htmlacademy.ru/javascript/24/criteries#d14).
Не забывай про наименование обработчиков (см. https://up.htmlacademy.ru/javascript/24/criteries#d4)

2021-11-01 15:58 UTC, KrapivinAV commented on js/form/validate-form.js
> +      } else if (guestQuantity.value === item.guests) {
Аналогично - не явно применение альтернативной ветки

2021-11-02 16:41 UTC, Karaterra commented
На кнопку reset навесил возврат к значению placeholder. Остальное сбрасывается и так.

2021-11-04 06:40 UTC, KrapivinAV approved these changes
Теперь все нормально

2021-11-04 06:40 UTC, merged